/// Flutter icons WellbeingIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WellbeingIcons
///      fonts:
///       - asset: fonts/WellbeingIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WellbeingIcons {
  WellbeingIcons._();

  static const _kFontFam = 'WellbeingIcons';
  static const String _kFontPkg = null;

  static const IconData biceps = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbell = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meditation = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData running = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sofa = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
